services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "18000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=config.settings